# see _data/meta.yml (so you don't have to restart jekyll to see changes)
baseurl: /
url: https://foundsound.me
permalink: pretty
sort_by: year, month
markdown: kramdown
kramdown:
  parse_block_html: true
plugins:
  - jekyll-feed
  - jekyll-sitemap
include: ['_pages']